export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
    LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
    SET_USER:'SET_USER',
    SET_SIGNIN_MODAL:'SET_SIGNIN_MODAL',
    SET_SIGNUP_MODAL:'SET_SIGNUP_MODAL',
    SET_IS_AUTHORIZED:'SET_IS_AUTHORIZED'
}